Some new fix

diff --git a/templates/lxc-debian-sk b/templates/lxc-debian-sk
--- a/templates/lxc-debian-sk
+++ b/templates/lxc-debian-sk
@@ -13,17 +13,28 @@
 
 # This library is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
- # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 # Lesser General Public License for more details.
 
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 
+SUITE=${SUITE:-wheezy}
+MIRROR=${MIRROR:-http://cdn.debian.net/debian}
+
 configure_debian()
 {
     rootfs=$1
     hostname=$2
+
+    # squeeze only has /dev/tty and /dev/tty0 by default,
+    # therefore creating missing device nodes for tty1-4.
+    for tty in $(seq 1 4); do
+        if [ ! -e $rootfs/dev/tty$tty ]; then
+            mknod $rootfs/dev/tty$tty c 4 $tty
+        fi
+    done
 
     # configure the inittab
     cat <<EOF > $rootfs/etc/inittab
@@ -39,10 +50,13 @@ l6:6:wait:/etc/init.d/rc 6
 # Normally not reached, but fallthrough in case of emergency.
 z6:6:respawn:/sbin/sulogin
 1:2345:respawn:/sbin/getty 38400 console
-c1:12345:respawn:/sbin/getty -n -l /bin/bash 38400 tty1 linux
+c1:12345:respawn:/sbin/getty 38400 tty1 linux
+c2:12345:respawn:/sbin/getty 38400 tty2 linux
+c3:12345:respawn:/sbin/getty 38400 tty3 linux
+c4:12345:respawn:/sbin/getty 38400 tty4 linux
+p6::ctrlaltdel:/sbin/init 6
+p0::powerfail:/sbin/init 0
 EOF
-
-    mknod -m 0600 $rootfs/dev/tty1 c 136 0
 
     # disable selinux in debian
     mkdir -p $rootfs/selinux
@@ -62,16 +76,10 @@ EOF
 $hostname
 EOF
 
-    # reconfigure some services
-    if [ -z "$LANG" ]; then
-        chroot $rootfs locale-gen en_US.UTF-8
-        chroot $rootfs update-locale LANG=en_US.UTF-8
-    else
-        chroot $rootfs locale-gen $LANG
-        chroot $rootfs update-locale LANG=$LANG
-    fi
+    LANG="C"
 
     # remove pointless services in a container
+    chroot $rootfs /usr/sbin/update-rc.d -f checkroot.sh remove
     chroot $rootfs /usr/sbin/update-rc.d -f umountfs remove
     chroot $rootfs /usr/sbin/update-rc.d -f hwclock.sh remove
     chroot $rootfs /usr/sbin/update-rc.d -f hwclockfirst.sh remove
@@ -80,6 +88,12 @@ EOF
     echo "Root password is 'root', please change !"
 
     return 0
+}
+
+cleanup()
+{
+    rm -rf $cache/partial-$SUITE-$arch
+    rm -rf $cache/rootfs-$SUITE-$arch
 }
 
 download_debian()
@@ -93,33 +107,36 @@ isc-dhcp-client,\
 netbase,\
 net-tools,\
 iproute,\
-vim,\
-mc,\
 iputils-ping,\
 openssh-server
 
     cache=$1
     arch=$2
 
+    trap cleanup EXIT SIGHUP SIGINT SIGTERM
     # check the mini debian was not already downloaded
-    mkdir -p "$cache/partial-$arch"
+    mkdir -p "$cache/partial-$SUITE-$arch"
     if [ $? -ne 0 ]; then
-        echo "Failed to create '$cache/partial-$arch' directory"
+        echo "Failed to create '$cache/partial-$SUITE-$arch' directory"
         return 1
     fi
 
     # download a mini debian into a cache
     echo "Downloading debian minimal ..."
     debootstrap --verbose --variant=minbase --arch=$arch \
-        --include $packages \
-        squeeze $cache/partial-$arch http://ftp.debian.org/debian
+        --include=$packages \
+        "$SUITE" "$cache/partial-$SUITE-$arch" $MIRROR
     if [ $? -ne 0 ]; then
         echo "Failed to download the rootfs, aborting."
         return 1
     fi
 
-    mv "$1/partial-$arch" "$1/rootfs-$arch"
+    mv "$1/partial-$SUITE-$arch" "$1/rootfs-$SUITE-$arch"
     echo "Download complete."
+    trap EXIT
+    trap SIGINT
+    trap SIGTERM
+    trap SIGHUP
 
     return 0
 }
@@ -132,33 +149,27 @@ copy_debian()
 
     # make a local copy of the minidebian
     echo -n "Copying rootfs to $rootfs..."
-    cp -a $cache/rootfs-$arch $rootfs || return 1
+    mkdir -p $rootfs
+    rsync -Ha "$cache/rootfs-$SUITE-$arch"/ $rootfs/ || return 1
     return 0
 }
 
 install_debian()
 {
-    cache="/var/cache/lxc/debian"
+    cache="@LOCALSTATEDIR@/cache/lxc/debian"
     rootfs=$1
-    mkdir -p /var/lock/subsys/
+    mkdir -p @LOCALSTATEDIR@/lock/subsys/
     (
-        flock -n -x 200
+        flock -x 200
         if [ $? -ne 0 ]; then
             echo "Cache repository is busy."
             return 1
         fi
 
-        arch=$(arch)
-        if [ "$arch" == "x86_64" ]; then
-            arch=amd64
-        fi
+        arch=$(dpkg --print-architecture)
 
-        if [ "$arch" == "i686" ]; then
-            arch=i386
-        fi
-
-        echo "Checking cache download in $cache/rootfs-$arch ... "
-        if [ ! -e "$cache/rootfs-$arch" ]; then
+        echo "Checking cache download in $cache/rootfs-$SUITE-$arch ... "
+        if [ ! -e "$cache/rootfs-$SUITE-$arch" ]; then
             download_debian $cache $arch
             if [ $? -ne 0 ]; then
                 echo "Failed to download 'debian base'"
@@ -174,7 +185,7 @@ install_debian()
 
         return 0
 
-    ) 200>/var/lock/subsys/lxc
+        ) 200>@LOCALSTATEDIR@/lock/subsys/lxc-debian
 
     return $?
 }
@@ -183,20 +194,22 @@ copy_configuration()
 {
     path=$1
     rootfs=$2
-    name=$3
+    hostname=$3
 
-    mkdir -p /var/log/lxc/
+    grep -q "^lxc.rootfs" $path/config 2>/dev/null || echo "lxc.rootfs = $rootfs" >> $path/config
     cat <<EOF >> $path/config
-lxc.utsname = $name
+lxc.tty = 4
+lxc.pts = 1024
+lxc.utsname = $hostname
+
 lxc.network.type = veth
 lxc.network.name = veth0
 lxc.network.flags = up
 lxc.network.link = br0
 
-lxc.tty = 1
-lxc.console = /var/log/lxc/$name.log
-lxc.pts = 1024
-lxc.rootfs = $rootfs
+# When using LXC with apparmor, uncomment the next line to run unconfined:
+#lxc.aa_profile = unconfined
+
 lxc.cgroup.devices.deny = a
 # /dev/null and zero
 lxc.cgroup.devices.allow = c 1:3 rwm
@@ -215,11 +228,8 @@ lxc.cgroup.devices.allow = c 5:2 rwm
 lxc.cgroup.devices.allow = c 254:0 rwm
 
 # mounts point
-lxc.mount.entry=proc $rootfs/proc proc nodev,noexec,nosuid 0 0
-lxc.mount.entry=devpts $rootfs/dev/pts devpts defaults 0 0
-lxc.mount.entry=sysfs $rootfs/sys sysfs defaults  0 0
-
-lxc.tty = 1
+lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
+lxc.mount.entry = sysfs sys sysfs defaults  0 0
 EOF
 
     if [ $? -ne 0 ]; then
@@ -232,7 +242,7 @@ EOF
 
 clean()
 {
-    cache="/var/cache/lxc/debian"
+    cache="@LOCALSTATEDIR@/cache/lxc/debian"
 
     if [ ! -e $cache ]; then
         exit 0
@@ -240,7 +250,7 @@ clean()
 
     # lock, so we won't purge while someone is creating a repository
     (
-        flock -n -x 200
+        flock -x 200
         if [ $? != 0 ]; then
             echo "Cache repository is busy."
             exit 1
@@ -250,7 +260,7 @@ clean()
         rm --preserve-root --one-file-system -rf $cache && echo "Done." || exit 1
         exit 0
 
-    ) 200>/var/lock/subsys/lxc
+    ) 200>@LOCALSTATEDIR@/lock/subsys/lxc-debian
 }
 
 usage()
@@ -264,7 +274,7 @@ EOF
 options=$(getopt -o hp:n:c -l help,path:,name:,clean -- "$@")
 if [ $? -ne 0 ]; then
         usage $(basename $0)
-    exit 1
+        exit 1
 fi
 eval set -- "$options"
 
@@ -301,7 +311,14 @@ if [ "$(id -u)" != "0" ]; then
     exit 1
 fi
 
-rootfs=$path/rootfs
+# detect rootfs
+config="$path/config"
+if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
+    rootfs=`grep 'lxc.rootfs =' $config | awk -F= '{ print $2 }'`
+else
+    rootfs=$path/rootfs
+fi
+
 
 install_debian $rootfs
 if [ $? -ne 0 ]; then
